spring:
  application:
    name: mnay-server
  profiles:
    include: common,auth,workflow,mysql
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: ${JPA_OPEN_IN_VIEW:false}
    ## 默认关闭
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        auto_quote_keyword: true
        generate_statistics: false
        default_batch_fetch_size: ${BATCH_FETCH_SIZE:1000}
        order_by.default_null_ordering: last
        jdbc:
          time_zone: Asia/Shanghai
          lob:
            non_contextual_creation: true
          # jpa批量插入设置，一次性批量插入1000条（需要在jdbc连接mysql的url上加上“rewriteBatchedStatements=true”）
          batch_size: 1000


server:
  port: ${SERVER_PORT:8080}


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/
    ## 需要时设置开启
    enabled: ${SWAGGER_ENABLE:true}
    ## 默认不展开，方便查看
    doc-expansion: none
    ## model展开的深度
    default-model-expand-depth: 10
    # API 排序
    tags-sorter: alpha
    # Http方法排序
    operations-sorter: method
  packages-to-scan: cn.mnay.controller

mnay:
  # 异步线程池自定义配置
  async-thread-pool:
    enable: true

# minio配置
minio:
  endpoint: ${MINIO_ENDPOINT:localhost:9000} #Minio服务所在地址
  bucketName: ${MINIO_BUCKET_NAME:files} #桶名称
  accessKey: ${MINIO_ACCESS_KEY:mnayuser} #访问的key
  secretKey: ${MINIO_SECRET_KEY:root@123456} #访问的密钥

dubbo:
  application:
    name: ApplicationStarter
    qos-enable: true
    qos-port: 33333
    qos-accept-foreign-ip: false
  config-center:
    address: zookeeper://127.0.0.1:2181
  registry:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
  provider:
    timeout: 30000
#  scan:
#    base-packages: cn.mnay.auth.service,cn.mnay.oss.service

## 日志配置
## 日志文件记录通过pm2来保存在服务器上，本地可以用logging.file.path,logging.file.name这两个配置进行配置
logging:
  pattern:
    console: "%white(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr(%5p) %clr(${PID:-}){magenta} %yellow([%X{traceId}]) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} : %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:-} [%X{traceId}] [%15.15t] %-40.40logger{39} : %m%n"
  level:
    root: info
    net.sf.json: error