spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:mnay}?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai&&allowPublicKeyRetrieval=true&allowMultiQueries=true&rewriteBatchedStatements=true}
    username: ${MYSQL_PASSWORD:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 50
      maximum-pool-size: 100
      max-lifetime: 120000
      idle-timeout: 50000
      connection-test-query: SELECT 1
